site_name: MkLorum
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.
theme:
    name: mkdocs
    locale: en
    custom_dir: my_theme_customizations/
    static_templates:
        - sitemap.html
    include_sidebar: false